### ISSUE TITLE
Preferred style convetions

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#100]
Feels like a good time to revisit some conventions of how we write our base styles. Can discuss in this issue and then update this list with final draft. 

My initial thoughts:

### Style conventions

1. Write composable utility classes for individual CSS rules. See [utility classes and separation of concerns](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/).

```scss
// ✅ Preferred
.rounded {
  border-radius: 0.25rem;
}

.border {
  border: 1px solid black;
}

// ❌ Discouraged
.border-rounded {
  border: 1px solid black;
  border-radius: 0.25rem;
}
```

... _unless_ you're writing a rule that composes the individual rules as a shortcut:

```scss
// ✅ Both utility classes and composed class
.rounded {
  border-radius: 0.25rem;
}

.border {
  border: 1px solid black;
}

.border-rounded {
  @extend .border;
  @extend .rounded;
}
```

2. Prefer CSS rules to SCSS mixins for non-dynamic utility classes. See [extends vs mixins](https://medium.com/stories-from-the-keen/when-to-use-extends-vs-mixins-in-sass-b09d55abd53).

```scss
// ✅ Preferred
.uppercase {
  text-transform: uppercase;
}

div {
  @extend .uppercase;
}

// ❌ Discouraged
@mixin uppercase {
  text-transform: uppercase;
}

div {
  @include uppercase;
}
```

3. Prefer (prefixed) CSS variables to SCSS variables.

```scss
// ✅ Preferred
:root {
  --colour-tr-orange: #fa6400;
}

div {
  color: var(--colour-tr-orange);
}

// ❌ Discouraged
$tr-orange: #fa6400;

div {
  color: $tr-orange;
}
```
... but always prefer CSS variables already defined in the theme:
```scss
// ✅ Preferred
div {
  color: var(--theme-colour-text-primary);
}

// ❌ Discouraged
:root {
  --colour-tr-black: #404040;
}

div {
  color: var(--colour-tr-black);
}
```

4. Create important variants of utility classes. See [important modifier](https://tailwindcss.com/docs/configuration#important-modifier).

```scss
// ✅ Preferred
.uppercase {
  text-transform: uppercase;
}

.\!uppercase {
  text-transform: uppercase !important;
}
```
... which can then be used like:

```html
<p class="!uppercase">Uppercase text</p>
```
