### ISSUE TITLE
Change theme usage in the footer referral to always use Knowledge

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#151]
Currently it uses `--theme-font-family-note: var(--theme-font-family-sans-serif);` So, changing the sans-serif font changes the footer as well. This should use `font-knowledge` instead, right @hobbes7878?
<img width="1214" alt="image" src="https://github.com/reuters-graphics/graphics-components/assets/7580745/a9c060f0-757b-48b4-a1d7-b7c8e249d892">

**Comment by hobbes7878** [comment]
Yes. Can you get me a PR that writes a CSS variable override rule for the outermost parent container of that component?

```scss
div.outermost {
  --theme-font-family-sans-serif: 'Knowledge', etc.;
}
```
