### ISSUE TITLE
Additional note for pattern themes

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#55]
Need to also override mobile menu background with:

```SCSS
header + .overlay {
  background: #222 !important;
}
```
